# Coder Academy and Qantas Masterclass


This notebook has the following sections...

* Part 1: Problem introduction
* Part 2: Using the notebook
* Part 3: Background on image processing
* Part 4: Convolutional neural networks
* Part 5: Creating geographic boundaries
* Part 6: Building the model

You can pull up the **Table of contents** on the left hand-side in colab to skip around the notebook. We also **strongly** recommend going to your **Runtime->Change Runtime Type** and switching **Hardware Accelerator** to **GPU**.

<br>

![](https://cdn.newsapi.com.au/image/v1/102d01fda4089f60b42be982ee172c81)

<br>

## Part 1: Problem introduction

---

### What are we trying to do?

As explained, [Qantas](qantas.com.au) serves a number of destinations around the world, many of which might _peak_ the interests of similar travelers.

<table>
    <tr>
        <td><img src="http://www.waitakinz.com/assets/Tourism-Operators/images/_resampled/ScaleHeightWyI1NTAiXQ/p-25EA0C05-D4C6-FFD9-45298B90A92328C9-2544003.jpg" style="width:500px; height:300px"></td>
        <td><img src="https://static.independent.co.uk/s3fs-public/thumbnails/image/2018/06/27/15/gettyimages-699088407.jpg" style="width:500px; height:300px"></td>
    </tr>
    <tr>
        <td><span style="font-size:16px">Do you like traveling to the Southern Alps??</span></td>
        <td><span style="font-size:16px">Why not try the Swiss Alps...and fly with Qantas, or a partner?</span></td>
    </tr>
</table>

It would be amazing if Qantas could identify by a picture _where_ someone was traveling, and potentially recommend them to travel to a _different_ but _similar_ location.

In this workshop, we'll create an algorithm to **classify images based upon their location**. We'll then see how this algorithm could be used to recommend _new_ destinations based upon its similarity to the classified images.


---


<img src="https://github.com/CoderAcademyEdu/data_science_sc_student/blob/master/img/Qantas_Classification_Biz.png?raw=1" width="750">

---


### Data Pipeline

In this session, we'll build a **data pipeline** to build an image relationship model. From [wikipedia](https://en.wikipedia.org/wiki/Pipeline_(computing))...

> In computing, a **pipeline** (also known as a **data pipeline**) is a set of data processing elements connected in series, where the output of one element is the input of the next one. The elements of a pipeline are often executed in parallel or in time-sliced fashion.

Data pipelines deal with the process of collecting, modifying and analysing a dataset towards some goal. Here's a picture of a data pipeline from [this medium blog](https://medium.com/the-data-experience/building-a-data-pipeline-from-scratch-32b712cfb1db)...

![](https://cdn-images-1.medium.com/max/1600/1*8-NNHZhRVb5EPHK5iin92Q.png)

For the rest of this lesson we'll build-up this pipeline. We will....

1. Analyse an image, and learn about how computers **think about images**
2. Develop a way **differentiate images by location**
3. Create a **classification algorithm** to be able to predict _where_ an image comes from
4. See our **prediction algorithm live!**

## Part 2: Using the notebook

---

### What is Python?

Python is an _interpretive_ programming language invented in the 1980s. It's actually named after Monty Python and Holy Grail. In this class we'll be using Python to build our machine learning algorithms. 

#### Why learn Python?

Python has gained popularity because it has an easier syntax (rules to follow while coding) than many other programming languages. Python is very diverse in its applications which has led to its adoption in areas such as data science and web development.

All of the following companies actively use Python:

![Image](https://www.probytes.net/wp-content/uploads/2018/08/appl.png)

### How do I interact with this notebook?

A Jupyter Notebook is an interactive way to work with code in a web browser. Jupyter is a pseudo-acronym for three programming languages: Julia, python and (e)r. Notebooks provide a format to add instructions + code in one file, which is why we're using it!

We'll quickly do some practice to introduce you how to use this notebook. For a list of keyboard shortcuts you can take a look at [Max Melnick's](http://maxmelnick.com/2016/04/19/python-beginner-tips-and-tricks.html) beginner tips for Jupyter Notebook.

Here's a quick run down of some of the most basic commands to use:

- A cell with a **<span style="color:blue">blue</span>** background is in **Command Mode**. This will allow you to toggle up/down cells using the arrow keys. You can press enter/return on a cell in command mode to enter edit mode

- A cell with a **<span style="color:green">green</span>** background is in **Edit Mode**. This will allow you to change the content of cells. You can press the escape key on a cell in command mode to enter edit mode

- To run the contents of a cell, you can type:
  - `cmd + enter`, which will run the cotents of a cell and keep the cursor in place
  - `shift + enter`, which will run the contents of a cell, and move the cursor to the next cell (or create a new cell)

### Exercise

Edit the below by changing "Gretchen" to your own name by entering edit mode, and then running the cell using the directions above.

In [0]:
print("Hello, Gretchen!")

Before we dig deep into the problem. Let's import some **modules** that will help us throughout the rest of the masterclass.

> For those who do not know, a **module** or **library** is a set of python code-files that bring new capabilities into our programs. We need to `import` modules into our session, because not all python modules are available when we begin our notebook session. Thus, we can import exactly what we need for the specific code we create.

In case you want to know more about the modules we will utilise today, here's a quick table.

| Module name | Description |
|-------------|-------------|
| [numpy](https://www.numpy.org/) | A library for numerical and mathematical manipulation in Python |
| [scipy](https://www.scipy.org/) | Contains many modules for scientific computing in Python |
| [matplotlib](https://matplotlib.org/) | Creates plots and visualisations |
| [PIL](https://pillow.readthedocs.io/en/stable/) | Allows for image processing and manipulation |
| [sklearn](https://scikit-learn.org/) | Contains functions and methods for the creation and analysis of machine learning algorithms  |
| [keras](https://keras.io/) | A library that allows for manipulations of neural networks, powered by other libraries, such as [Tensorflow](https://www.tensorflow.org/) |
| [gzip](https://docs.python.org/3/library/gzip.html) | Allows for the compression and decompression of files |
| [json](https://docs.python.org/3/library/json.html) | Encodes and decodes json files |
| [requests](https://2.python-requests.org/en/master/) | Creates an interface to send HTTP requests in Python |
| [urllib](https://docs.python.org/3/library/urllib.html) | Provides an interface for working with URLs |
| [pandas](https://pandas.pydata.org/) | A Python library for manipulating tabular data |
| [pyqtree](https://github.com/karimbahgat/Pyqtree) | Creates an efficient way for manipulating geographic data |
| [time](https://docs.python.org/3/library/time.html) | Library for monitoring code runtime | 
| [os](https://docs.python.org/3/library/os.html) | Provides methods for accessing operating system information |
| [tarfile](https://docs.python.org/3/library/tarfile.html) | Reads/writes tar files |
| [folium](https://python-visualization.github.io/folium/quickstart.html) | Mapping visuals in Python |

In [0]:
# Scipy and numpy
import numpy as np
from scipy import signal
from scipy import ndimage

# Plotting
import matplotlib.pyplot as plt
from matplotlib import cm
from PIL import Image
%matplotlib inline

# Sklearn 
from sklearn import datasets
from sklearn.model_selection import train_test_split

# Keras
import keras
from keras.preprocessing import image
from keras.models import Sequential
from keras.layers import Dense, Flatten
from keras.applications.inception_v3 import InceptionV3, preprocess_input
from keras.layers import Dropout
from keras.models import Model
from keras.layers import Conv2D, GlobalAveragePooling2D

# Requests,json and URL libraries
from gzip import decompress
from json import loads
from requests import get
import urllib

# Pandas
import pandas as pd

# Pyqtree
!pip install pyqtree
from pyqtree import Index

# Time
import time

# OS
import os

# Tarfile
import tarfile

# Folium
import folium

## Part 3: Background on image processing

---

### What is an image...in the mind of a computer?

Let's start to get a feel about how a computer can process an image. To do that, we'll upload a single image into our Python notebook, and analyse some characteristics of the image. We'll use the [keras](https://keras.io/) library, to upload our image.

In [0]:
# Open the image
image_file = 'https://raw.githubusercontent.com/CoderAcademyEdu/data_science_sc_student/master/data/Masterclass_Images/32704191297_81ba56ef37.jpg'
img = Image.open(urllib.request.urlopen(image_file))

# Make the image an array
img_array = image.img_to_array(img)

# Print the array shape
print('The image shape: ')
print(img_array.shape)
print("\n")

# Print a section of the array and then a specific pixel
print('A subsection of the image array: ')
print(img_array[0:10, 0:10, 0])
print("\n")

print('A single pixel: ')
print(img_array[-1, -1, :])
print("\n")

# Display the image
img

The code did something a little funky here...it converted the image to an array of numbers, something that looked like this...

---

A subsection of the image array: 
```python
[[ 59.  44.  47.  52.  52.  55.  52.  52.  50.  56.]
 [ 51.  53.  53.  49.  50.  54.  54.  57.  55.  46.]
 [ 49.  56.  51.  51.  57.  55.  52.  52.  52.  51.]
 [ 52.  53.  49.  55.  57.  52.  54.  54.  53.  59.]
 [ 53.  51.  53.  56.  49.  50.  57.  55.  53.  38.]
 [ 54.  50.  56.  53.  51.  57.  52.  45.  57.  95.]
 [ 56.  50.  56.  51.  57.  59.  50.  75. 142.  89.]
 [ 56.  52.  59.  50.  54.  49.  58. 139.  37. 118.]
 [ 70.  74.  67.  54.  52.  37. 108.  80.  96. 160.]
 [ 60.  80.  71.  68.  61.  62. 124.  88. 140. 140.]]
```

---

It also printed out a single **pixel** in the image. Something that looked like this...

---

```
A single pixel: 
[102. 131. 147.]
```
---

Let's dig into this a little bit more.

#### Anatomy of an image

The following picture visualises how a computer thinks about an image.

---

![](https://github.com/CoderAcademyEdu/data_science_sc_student/blob/master/img/Image_Anatomy.png?raw=1)

---

Let's break this down.

* The square in the bottom right-hand corner represents a single point in the image. We call each point in an image a **pixel**. Pixels are like tiny little squares, each with an individual colour.
* All colours in an image can be represented by three numbers. The numbers represent the portion of a pixel that is **red, blue, or green**. We call these **RGB values**.
  * The reason red, green and blue were chosen is because these are additive primary colours, meaning we can make any other colours from these three primary colours.
  * Each number for R, G or B, will be in the range 0-255, meaning there are 256 distinct possibilities. The reason there are 256 actually is based upon how a computer stores this value in memory (it uses an 8-bit number).
* The image has a **size**, that dictates how many of these RGB values there are. In this image there are **281 rows, and 500 columns** of pixels.

### Convolutions

#### How do computers differentiate between images?

Let's take a look of two different images, one from the Sydney Opera house, and the other of the Southern Alps.

<table>
    <tr>
        <td><img src="https://github.com/CoderAcademyEdu/data_science_sc_student/blob/master/data/Masterclass_Images/32805115817_3ce92c9bd4.jpg?raw=1" style="width:400px; height:300px"></td>
        <td><img src="https://github.com/CoderAcademyEdu/data_science_sc_student/blob/master/data/Masterclass_Images/32704191297_81ba56ef37.jpg?raw=1" style="width:400px; height:300px"></td>
    </tr>
</table>

---

### Thought exercise

Using the ideas of **pixels** and **colours** as before. Re-draw these images on two pieces of paper, in the **simplest form possible**. Try to ask yourself...what are the **features** that distinguish these two images? Think about...

* Distinct **shapes** in an image
* Distinct **colours** in an image


---

Let's see how a computer can translate the shapes into an image into a simpler form. Run the following code which will apply a **filter** to an image. What's the filter doing?

In [0]:
# Add filter
filter_1 = [
    [-1, 0, 1],
    [-2, 0, 2],
    [-1, 0, 1]
]

# Convert to black and white
bw = np.dot(img_array, [0.21, 0.72, 0.07]).astype(np.uint8)

# Convolve
output = ndimage.convolve(bw, filter_1, mode='constant')


# Show
plt.figure(figsize=(10, 5))
plt.imshow(output, cmap='Greys')

Here's another filter. What's going on in this one?

In [0]:
# Add filter
filter_2 = [
    [-1, -2, -1],
    [0, 0, 0],
    [1, 2, 1]
]


# Convolve
output = ndimage.convolve(bw, filter_2, mode='constant')

# Show
plt.figure(figsize=(10, 5))
plt.imshow(output, cmap='Greys')

### Convolution

These filters are using an operation called **convolution**. Convolution is a complex operation, but it allows us to change and filter an image to specific important parts. Here's how convolution works, mathematically.


![](https://media.giphy.com/media/i4NjAwytgIRDW/giphy.gif)


As you can see, there is a sliding orange **array or matrix** that moves across an image. At each point, the image pixels are being multiplied by the small numbers, and summed together. The result of this sliding matrix is posted on the right hand side.

We call the moving array the **kernel** of the image. In our examples of above, we used two kernels, written below.


```python
filter_1 = [
    [-1, 0, 1],
    [-2, 0, 2],
    [-1, 0, 1]
]

filter_2 = [
    [-1, -2, -1],
    [0, 0, 0],
    [1, 2, 1]
]
```

A lot of image editing software uses convolution. [Here's a great link](http://setosa.io/ev/image-kernels/) to show you different kinds of filters.

### Exercise

Play with the code below to apply different kernels to the image. See what each kernel does. Feel free to change-up the filters and create your own.

In [0]:
# Create filters
filters = [
    [
        [0.0625, 0.125, 0.0625],
        [0.125, 0.25, 0.125],
        [0.0625, 0.125, 0.0625]
    ],
    [
        [0, -1, 0],
        [-1, 5, -1],
        [0, -1, 0]
    ],
    # Insert your filter here
    [
        [0, 0, 0],
        [0, 1, 0],
        [0, 0, 0]
    ]
]

# CHANGE "filter_type = 0" to "filter_type = 1" or "filter_type = 2" to change the filter
filter_type = 2
output = ndimage.convolve(bw, filters[filter_type], mode='constant')

# Show
plt.figure(figsize=(10, 10))
plt.subplot(2, 1, 1)
plt.imshow(bw, cmap='Greys')
plt.title('Original image')
plt.subplot(2, 1, 2)
plt.imshow(output, cmap='Greys')
plt.title('Convolved Image')

So, as you've likely noticed, different filters can extract particular features OF an image. Now let's go back to our original problem...if we have pictures of the southern alps, and we have pictures of the opera house, how do we distinguish what photographic features distinguish the opera house from the alps?

## Part 4: Convolutional neural networks

---

The beauty of **machine learning** is that it allows computers to find out what are the distinguishing features of an image by crunching millions upon millions of pixels for us, finding nuances that are not readily noticable by the human eye, but are noticable in **patterns amongst pixel values**.

So you might be asking, how do we do this? Let's take a little detour into **classification**.

### What is classification?

> **Classification** is an area of machine learning that tries to build **algorithms** that input a set of data, and output a class label. In our case, we want to build algorithms that **input an image** and output whether an algorithm belongs to one of two classes, the **opera house**, or the **Southern Alps**.

If this is too complicated...this [example](https://www.youtube.com/watch?v=vIci3C4JkL0) might help.

<img src="https://d3ansictanv2wj.cloudfront.net/Figure_1-71076f8ac360d6a065cf19c6923310d2.jpg" width="500">

In math speak, we are essentially trying to define a **function** where the input is an image, and the output is either "opera house" or "Southern Alps".

```
f(image) = 0 if image is "Opera House"
f(image = 1 if image is "Southern Alps"
```

To do this, we can train what is called a **convolutional neural network**.

### What is a neural network?


A **neural network** is a type of machine learning algorithm that can be used to classify things. It was actually created to resemble how neurons in the brain connect with each other, and the models look like the gif below.

![](https://thumbs.gfycat.com/DeadlyDeafeningAtlanticblackgoby-max-1mb.gif)

In the image, we're feeding the **image with the number 7** to the **input layer** of the network. The image is 28x28 pixels, which is why there are a total of 784 input neurons (28 x 28 = 784). The network has been trained to recognise the seven, and you can see as there are certain nodes/edges activated in the **middle/hidden layers**, and **output layers** that are specifically activated when a seven is inputted in the network.

Since this is a network with input, hidden and output layers, we call this type of neural network a **deep neural network**, and this type of machine learning **deep learning**.

Let's play around with training a neural network to recognise digits. The following code will load a set of [pictures that represent digits from the sklearn library](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_digits.html#sklearn.datasets.load_digits)/

In [0]:
# Load the digits
digits = datasets.load_digits()

# Show the first digit
print('The first digit is a: ' + str(digits.target[0]))
print('The size of the images are: ' + str(digits.images[0].shape))
plt.imshow(digits.images[0])

Now let's build up a small neural network with three layers...

* An input layer layer, with 64 total inputs
* One hidden layer
* An output layer, with labels 0-9 at the end

In [0]:
# Create a model
model = Sequential()

# Input layer
model.add(Flatten())
# Hidden layer
model.add(Dense(32, activation='relu'))
# Output layer
model.add(Dense(10, activation='softmax'))

# Compile
model.compile(
    loss='categorical_crossentropy',
    optimizer='rmsprop',
    metrics=['accuracy']
)

# Fit
train_x, test_x, train_y, test_y = train_test_split(digits.images, digits.target)

# Reformat y
train_y_new = []
for y in train_y:
    temp = np.zeros(10)
    temp[y] = 1
    train_y_new.append(temp)
train_y_new = np.array(train_y_new)

# Train
model.fit(train_x, train_y_new, batch_size=32, epochs=10)

#### Optional side note...

For those who are analysing the code above, you might see we use something called `train_test_split`, which splits our data into two different datasets...

1. A dataset called `train` that we use to fit the model
2. Another dataset called `test`, which we later use to analyse how _well_ our model performs

Why do we not train and test model performance on the same dataset? Think about studying for a math test...if we practiced using just the problems we already have completed, we'd get really good at understanding those problems, but not necessarily be able to understand _new_ information. 

In machine learning, we do not want computers to just understand the data we have at hand, we want to see how it will predict _new_ data it has not been exposed to you. Thus, test sets are _held out_ of model training, and are used to simulate what it's like to expose our algorithms to _new_ information.

### Exercise

The following code will use our model to predict an output, and then show the true image.

Play around by changing the `ind` variable (it can be any number between 0-449). Are there any numbers that tend to be wrong more than others, or did we do a good job?

In [0]:
# CHANGE INDEX HERE
ind = 132

# Predict
y_pred = model.predict(test_x[[ind]])
# Get index of max
y_pred = np.argmax(y_pred)

print('Predict number: ' + str(y_pred))
plt.imshow(test_x[ind])

#### Optional: Adding complexity

So, we just made what's called a **fully connected network** with a lot of **dense layers**. Based upon the amount of layers we made, and neurons, the model tuned the following number of parameters:

In [0]:
# Print model parameters
model.summary()

As you can see there are a total of (65 * 32) + (33 * 10) = 2,410 parameters we train.

Now this model fitting isn't going to work very well on more complex detections. Let's upload images of the Opera House and the Southern Alps.

In [0]:
# Targets
target_values = []

# Upload opera house
file_tmp = urllib.request.urlretrieve(
    "https://raw.githubusercontent.com/CoderAcademyEdu/data_science_sc_student/master/data/Masterclass_Images/Opera_House.tar.gz", filename=None
)[0]
base_name = os.path.basename(file_tmp)
file_name, file_extension = os.path.splitext(base_name)
tar = tarfile.open(file_tmp, 'r')

opera_house_array = []
for m in tar.getmembers():
    if '.jpg' in m.name:
        img = tar.extractfile(m.name)
        img = image.load_img(
            img, 
            target_size=(299, 299)
        )
        opera_house_array.append(image.img_to_array(img).astype(np.uint8))
        target_values.append(0)

In [0]:
# Upload southern alps
file_tmp = urllib.request.urlretrieve(
    "https://raw.githubusercontent.com/CoderAcademyEdu/data_science_sc_student/master/data/Masterclass_Images/Southern_Alps.tar.gz", filename=None
)[0]
base_name = os.path.basename(file_tmp)
file_name, file_extension = os.path.splitext(base_name)
tar = tarfile.open(file_tmp, 'r')

southern_alps_array = []
for m in tar.getmembers():
    if '.jpg' in m.name:
        img = tar.extractfile(m.name)
        img = image.load_img(
            img, 
            target_size=(299, 299)
        )
        southern_alps_array.append(image.img_to_array(img).astype(np.uint8))
        target_values.append(1)
        

# Combine
img_data = np.array(opera_house_array + southern_alps_array)
target_values = np.array(target_values)

Let's use the same network configuration we used earlier, and see how our model performs. We'll have to adjust our model slightly, since the input images are now 200 x 200 pixels, with RGB values. Also, we are only trying to predict two values, where 

```
0 = Sydney Opera House
1 = the Southern Alps
```

In [0]:
# Create a model
model = Sequential()

# Input layer
model.add(Flatten())
# Hidden layer
model.add(Dense(200, activation='relu'))
# Output layer
model.add(Dense(1, activation='sigmoid'))

# Compile
model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

# Split dataset
train_img_x, cross_val_img_x, train_img_y, cross_val_img_y = train_test_split(
    img_data, target_values
)

# Fit
model.fit(x=train_img_x, y=train_img_y, batch_size=32, epochs=1)

You might notice that the training accuracy is not going up!! There's a few reasons why this might happen...

* We're using a pretty small dataset
* The dataset we have does not distinguish well between the Opera House and the Southern Alps
* Our model isn't complicated enough

So we have a few choices to make...

1. We could build a more complicated model
2. We could try to scrape more data
3. We could augment our dataset using the data we currently have, by adding random noise

Let's pretend for the purposes of this workshop (2) is off the table. So...let's start with (1).

To complicate our model, we could add more layers, and thus have more parameters that are trained in the model to capture nuances. Let's try this out in the code below, and time the training time. We'll also print some summary data at the end of the model.

In [0]:
# Start
start = time.time()

# Add more layers
model = Sequential()

# Input layer
model.add(Flatten())
# Hidden layers
model.add(Dense(200, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(50, activation='relu'))
# Output layer
model.add(Dense(1, activation='sigmoid'))

# Compile
model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

# Fit
model.fit(x=img_data, y=target_values, batch_size=32, epochs=1)

# End time
end = time.time()
print("\n")
print('Training took a total of: %0.2f seconds' % (end - start))

# Model summary
model.summary()

That's a lot of parameters, and not much payoff!

Each fully connected layer creates (the layer size + 1) * (the next layer size) parameters to train, and unless we add a _ton_ more, we're not going to get much better accuracy. So instead, we'll use what's called **convolutional layers** to train the network, which will allow us to train layers with **far less parameters**.

### Convolutional layers

Convolutional layers work by finding **kernels**, or the **arrays we described earlier**, to pick-out interesting parts of images.

---

![](https://github.com/CoderAcademyEdu/data_science_sc_student/blob/master/img/Qantas_CNN_Image.png?raw=1)

---

We then use a small amount of fully connected layers at the end of the network to finish our model.

---

![](https://github.com/CoderAcademyEdu/data_science_sc_student/blob/master/img/CNN.png?raw=1)

---

Let's create our convolutional neural network. You'll see the network has some convolutional layers in it.

In [0]:
# Make model
convo_model = Sequential()

# Convolutional layers
convo_model.add(Conv2D(32, (3, 3), input_shape=(299, 299, 3), activation='relu'))
convo_model.add(GlobalAveragePooling2D())

# Fully connected layers
convo_model.add(Dense(200, activation='relu'))
convo_model.add(Dense(1, activation='sigmoid'))
# Compile
convo_model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

# Start
start = time.time()

# Fit
convo_model.fit(x=img_data, y=target_values, batch_size=32, epochs=1)

# End time
end = time.time()

print("\n")
print('Training took a total of: %0.2f seconds' % (end - start))

# Model summary
convo_model.summary()

Still...not great, but we are reaching slightly better acuracy with more parameters! The reality is that convolutional neural networks take _a lot of data_ to train properly, and we only have 300 images in our training dataset. They're more efficient still then fully-connected networks. 

What people typically do is utilise **pre-trained networks**, and fit these pre-trained networks to their specific dataset. Let's do that, by using [Google's Inception-v3 model](https://medium.com/@sh.tsang/review-inception-v3-1st-runner-up-image-classification-in-ilsvrc-2015-17915421f77c) as a base model to our network.

Let's build onto Google's model. Run the cell below to do the build.

In [0]:
# Create baseline_model
base_model = InceptionV3(weights='imagenet', include_top=False)
output = base_model.output
output = GlobalAveragePooling2D()(output)

# Add dense layers
output = Dense(200, activation='relu')(output)
output = Dropout(0.5)(output) # Dropout helps prevent overfitting
output = Dense(200, activation='relu')(output)
output = Dropout(0.5)(output)
output = Dense(1, activation='sigmoid')(output)

# Create model
inceptionv3_model = Model(inputs=base_model.input, outputs=output)

for layer in inceptionv3_model.layers[:249]:
    layer.trainable = False
for layer in inceptionv3_model.layers[249:]:
    layer.trainable = True
    
inceptionv3_model.compile(
    loss='binary_crossentropy',
    optimizer='rmsprop',
    metrics=['accuracy']
)

# Start
start = time.time()

# Train model
inceptionv3_model.fit(
    x=preprocess_input(img_data), 
    y=target_values, 
    batch_size=32, 
    epochs=2
)

# End time
end = time.time()

print("\n")
print('Training took a total of: %0.2f seconds' % (end - start))

### Exercise

The following code allows you to input any image using a URL within the `my_image` variable. It then uses the `inceptionv3_model` we just created to predict...is the image more like the **Opera House**, or the **Southern Alps**?

Play around with changing `my_image`. Think about when the answer is wrong or right.

In [0]:
# Insert image here
my_image = 'https://www.rockswalkingtours.com.au/wp-content/uploads/2017/07/ExlcusiveTours_CircularQuay_Large.jpg'

# Upload image and resize
image_open = Image.open(urllib.request.urlopen(my_image))
image_open = image_open.resize((299, 299))
image_array = image.img_to_array(image_open)

# Now predict
pred = inceptionv3_model.predict(preprocess_input(np.array([image_array])))

# Print result
if np.round(pred[0][0]) == 0:
    print('Model predicted: Sydney Opera House, with probability: %.2f' % (1 - pred))
else:
    print('Model predicted: Southern Alps, with probability: %.2f' % pred)
    
# Show
plt.imshow(image_array.astype(np.uint8))

## Part 5: Creating geographic boundaries

---

Let's review what we've done. Thus far we have...

* Examined how images are visualised by a computer
* Examined how we can use the **convolution** operation to extract meaningful features from an image
* Setup a **classification algorithm** using a **convolutional neural network** to classify images from two locations

What are we missing?? Well...people do not just travel to the Sydney Opera House, or the Southern Alps. There are millions (and likely more) of pictures online from different locations that Qantas and its partners travel to. The big question becomes...

> Given the images that exist online...how do we develop the **right classification labels** to be able to match people towards new travel locations??

---

<img src="https://github.com/CoderAcademyEdu/data_science_sc_student/blob/master/img/Qantas_Classification_Drawing.png?raw=1" width="600">

---

### Bounding boxes

We're going to use a technique based upon [this paper](https://arxiv.org/abs/1602.05314) by Google to develop a method to take images from a _ton_ of different locations, and figure out what labels our algorithm should utilise. The idea is simply...

* Use geolocated images, with a latitude and longitude per every image, to identify areas of dense photo activity
* Restrict these areas to areas with _a lot_ of Qantas customers
* Develop a classification algorithm to identify which area an image fits in

We call each area a **bounding box**, meaning it bounds a geographic area with a box, and each box can become a classification label.

For example, the following bounding boxes were built off of a training set with images from Central Australia, Cairns, Sydney, Melbourne and the Southern Alps. Each section of the graph has been given a class label.

---

<img src="https://github.com/CoderAcademyEdu/data_science_sc_student/blob/master/img/bounding_boxes.png?raw=1" width="500">


---


### Running the code

The following code can be used to create bounding boxes. We won't go over the code, but run it to enable it's use.

In [0]:
def loadLocations(df):
    """
    Create a location that can be used to make boxes
    
    :param df: the DataFrame with latitude and longitude location
    
    :return spindex: The object that can make the bounding boxes
    """
    # Makes a quad tree
    lonList = []
    latList = []
    # Creates a bounding box surrounding Australia and NZ (x_min, y_min, x_max, y_max)
    spindex = Index(max_items=200, bbox=(113.38, -50.00, 170, -10.83))
    count = 0
    # Inserts photos into box based upon location
    for index, row in df.iterrows():
        decimalLon, decimalLat = float(row['longitude']), float(row['latitude'])
        fStr = str(int(row['id'])) + '_' + str(row['secret']) + '.jpg'
        spindex.insert(fStr,(decimalLon,decimalLat,decimalLon,decimalLat))
        count+=1    
    return spindex

def walk(parent, boxes, num_data):
    """
    Take a walk to see if we should make a box
    
    :param parent: The parent of the current box
    :param boxes: The current boxes list
    :param num_data: The number of data points to create a box
    """
    # Get center of the bounding box
    boxStr = (
        str(parent.center[0]) + ',' + str(parent.center[1]) + ',' + str(parent.width) + ',' + str(parent.height)
    )
    images = []
    # Go through each image (if images exist)
    for node in parent.nodes:
        images.append(node.item)
    
    # If there exist num_data points in this area, create box
    if len(images) > num_data:
        boxes[boxStr] = images

    # Go through each child in the tree
    for child in parent.children:   
        walk(child, boxes, num_data)

def buildBoxes(spindex, num_data):
    """
    Build bounding boxes
    
    :input spindex: An index of location data points
    :input num_data: The number of data points
    
    :return boxes: The boxes
    """
    boxes = {}
    walk(spindex, boxes, num_data)
    return boxes

def drawDistribution(boxes, y=None, ref=None, categories=None):
    """
    Draw area with boxes
    
    :inputs boxes: The boxes
    """   
    m = folium.Map(location=[-25.3444, 131.0369], tiles="Mapbox Bright", zoom_start=4)
    keys = sorted(boxes.keys())
 
    # I can add marker one by one on the map
    if y is None:
        ref = dict(zip(boxes.keys(), range(len(boxes))))
        categories = range(len(boxes))
        y = np.array([0.1] * len(boxes))
    else:
        y = (y / y.max()) * 0.6
    for i in range(0, len(keys)):
        key = keys[i]
        lon, lat, width, height = key.split(',')
        lon=float(lon)
        lat=float(lat)
        width=float(width)
        height=float(height)
        folium.Rectangle(
            bounds=[[lat-height/2,lon-width/2],[lat-height/2,lon+width/2],[lat+height/2,lon+width/2],[lat+height/2,lon-width/2]],
            color='crimson',
            fill_opacity=float(y[categories[ref[key]]]),
            fill=True,
            fill_color='crimson'
        ).add_to(m)
    return m

When we create bounding boxes, there's an active choice about how many data points need to be in a certain geographic area to consider it a box. There's a trade-off to this...

* The more data points in a box, the more images, and the easier it is to train a CNN
* The less data points, the more geography specific boxes we have

Let's look at an example.

The [file downloaded here](https://www.australiantownslist.com/) has a list of longitude and latitude coordinates of Australian towns. What we can do is create bounding boxes based upon geographic density of towns being proximal to each other. Let's upload the file into a variable called `aus_towns`.

In [0]:
# Add Australia towns
aus_towns = pd.read_csv('https://raw.githubusercontent.com/CoderAcademyEdu/data_science_sc_student/master/data/au-towns-sample.csv')
aus_towns['secret'] = 'fill'

### Exercise

The variable `num_datapoints` controls how many data points (towns) need to be proximal to make a bounding box. Raise and lower num_datapoints to create different bounding boxes. You can see the boxes you've drawn using the link below.

In [0]:
# SET num_datapoints here
num_datapoints = 10

# Add the locations
sp = loadLocations(aus_towns)

# Create boxes
b = buildBoxes(sp, num_datapoints)

# Draw
drawDistribution(b)

Let's build boxes for an actual image dataset that is hosted on GitHub. You can see the images [here](https://github.com/dadler6/Australia_Images/blob/master/27597053638_6d0e4ec38c.jpg). It comprises images from five places in the area...

* The Sydney Opera House
* The Sourthern Alps
* Uluru
* Melbourne CBD
* Cairns

Run the following code which will create bounding boxes off of this dataset.

In [0]:
# Add data
aus_image_data = pd.read_csv('https://raw.githubusercontent.com/CoderAcademyEdu/data_science_sc_student/master/data/all_images.csv')

# SET num_datapoints here
num_datapoints = 50

# Add the locations
sp = loadLocations(aus_image_data.loc[aus_image_data['Downloaded'] == 1, :])

# Create boxes
b = buildBoxes(sp, num_datapoints)

# Boxes dict
aus_image_data['Box'] = None
for i in aus_image_data.index:
    for k in b.keys():
        if aus_image_data.loc[i, 'URL'].split('/')[-1] in b[k]:
            aus_image_data.loc[i, 'Box'] = k
category_boxes = dict(zip(
    aus_image_data.loc[aus_image_data['Downloaded'] == 1, 'Box'].unique(), 
    aus_image_data.loc[aus_image_data['Downloaded'] == 1, 'Photo_Category'].unique()
))

# Draw
drawDistribution(b)

## Part 6: Building the model

---

Let's now build our final model, and then for the rest of the masterclass, we'll let you have a go at changing up...

* The model
* The image to test out

Run the following code to upload our images from the GitHub repository.

In [0]:
def get_gzipped_json(url):
    temp = loads(decompress(get(url).content))
    for k in temp:
        temp[k] = np.array(temp[k])
    return temp

github_url = 'https://github.com/dadler6/Australia_Images/raw/master/'

# Upload
aus_img_dict = dict()
aus_img_dict.update(get_gzipped_json(github_url + 'images_0.json.gz'))
print('25% Uploaded')
aus_img_dict.update(get_gzipped_json(github_url + 'images_1.json.gz'))
print('50% Uploaded')
aus_img_dict.update(get_gzipped_json(github_url + 'images_2.json.gz'))
print('75% Uploaded')
aus_img_dict.update(get_gzipped_json(github_url + 'images_3.json.gz'))
print('100% Uploaded')

Now, let's add labels to each of our images.

In [0]:
# Image labels
categories = dict(
    zip(aus_image_data.Photo_Category.unique(), range(len(aus_image_data.Photo_Category.unique())))
)

# Now get each category
image_inputs = []
image_categories = []

# Iterate through each image
for k in aus_img_dict:
    # Get ID
    temp_id = int(k.split('_')[0])
    # Get the photo category
    cat = aus_image_data.loc[aus_image_data['id'] == temp_id, 'Photo_Category'].iloc[0]
    cat_list = np.zeros(len(aus_image_data.Photo_Category.unique()))
    cat_list[categories[cat]] = 1
    # Append to lists so ordering is consistent
    image_inputs.append(aus_img_dict[k])
    image_categories.append(cat_list)

# Make arrays
image_inputs = np.array(image_inputs)
image_categories = np.array(image_categories)

Let's look at a couple images for the data we just uploaded.

In [0]:
plt.imshow(image_inputs[0].astype(np.uint8))

In [0]:
plt.imshow(image_inputs[300].astype(np.uint8))

### Training the model

Let's train a final model to try and predict whether an inputted image is alike to the five locations within our dataset. We've started the code for you, but try and do the following create the dense layers. 

**NOTE**, the last dense layer should not have one output, but **5** because we have five different locations within our model.

The following code creates a `hidden layer:`

```python
output = Dense(OUTPUT_SIZE, activation='relu')(output)
```

The following code creates the `final layer:`
```python
output = Dense(OUTPUT_SIZE, activation='softmax')(output)
```

In addition, the `loss` when you compile the model needs to changed from `binary_crossentropy` to `categorical_crossentropy`.

In [0]:
# Create baseline_model
base_model = InceptionV3(weights='imagenet', include_top=False)
output = base_model.output
output = GlobalAveragePooling2D()(output)

# Add dense layers
output = Dense(200, activation='relu')(output)
output = Dropout(0.5)(output) # Dropout helps prevent overfitting
output = Dense(200, activation='relu')(output)
output = Dropout(0.5)(output)
output = Dense(5, activation='sigmoid')(output)

# Create model
final_model = Model(inputs=base_model.input, outputs=output)

for layer in final_model.layers[:249]:
    layer.trainable = False
for layer in final_model.layers[249:]:
    layer.trainable = True
    
final_model.compile(
    loss='categorical_crossentropy',
    optimizer='rmsprop',
    metrics=['accuracy']
)

# Start time
start = time.time()

# Train model
final_model.fit(
    x=preprocess_input(image_inputs), 
    y=image_categories, 
    batch_size=32, 
    epochs=5
)

# End time
end = time.time()

print("\n")
print('Training took a total of: %0.2f seconds' % (end - start))

In [0]:
# Insert image here
my_image = 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Moraine_Lake_17092005.jpg/270px-Moraine_Lake_17092005.jpg'

# Upload image and resize
image_open = Image.open(urllib.request.urlopen(my_image))
image_open = image_open.resize((299, 299))
image_array = image.img_to_array(image_open)

# Now predict
pred = final_model.predict(preprocess_input(np.array([image_array])))

# Print results
print('Model likelihoods: ')
df = pd.DataFrame(categories.items(), columns=['Category', 'Index'])
df['Likelihood'] = pred[0].round(3)
print(df[['Category', 'Likelihood']])

# Show
plt.imshow(image_array.astype(np.uint8))

# Draw distribution
drawDistribution(b, pred[0], category_boxes, categories)

The following code can be used to **predict where images are from** using the model. Change the `my_image` variable with an image URL of your choosing to change the image.

## Wrap-up

---

Thank you for attending our masterclass! We hope we _demystified_ a little bit of what actually occurs when you build a machine learning process. Big thank you to Natalie Ganderton and Daniel Walsh from Qantas for their time.

If you would like to download your work for today, please click **File->Download As->.html**. You will not be able to run the cells, but you will be able to view the material you learned within a web browser.

### Survey

We would appreciate it if you could complete a quick feedback survey for tonight's Masterclass. You can find the survey here: http://bit.ly/ml_qantas_survey

THANK YOU!!